### ISSUE TITLE
Benchmark against a standard approach

### ISSUE THREAD

**Issue by taqtiqa-mark** [mamcx/tree-flat#3]
I'm exploring options around custom types for collections - so arenas are out of my wheelhouse.

I find it difficult to get a sense of the performance of this vs what you might do using Rust std collections.

Without that information it is tough to justify investing time into implementing something that may yield insufficient benefit?

**Comment by mamcx** [comment]
Check the companion article https://www.elmalabarista.com/blog/2022-flat-tree/, it shows this crate is close to `Vec` performance for a tree structure, and compared against another crate that is among the best (but use a more "traditional" approach).

`Arenas` are the recommended way to implement Trees/Grahps:

https://stackoverflow.com/questions/34747464/implement-graph-like-data-structure-in-rust

That is what other crates like [EgoTree](https://docs.rs/ego-tree/0.6.2/ego_tree/) do.

What this crate improves is in HOW the data is layout inside the arena. Making it be EXACTLY in pre-order means the data is read linearly, instead of "jumping around" the indexes on the Arena(vec) of the tree (that is also faster than jumping around with pointers).

So (< as "slower than"):

```
Pointers < Arenas < Arena+Pre-order
```

**Comment by taqtiqa-mark** [comment]
Thank you or taking time to respond so promptly, and for the references.  Apologies for the vuageness, relatively new to Rust and I come from a non-CS background - arenas are new to me

I think I understand the constraints, and where your sweet-spot is - read only and known size. 

I was wondering how non-area approaches using std collections might perform, the [SO link](https://stackoverflow.com/a/34748519/152860) (thank-you) indicates there are many alternative ways:

> Two examples:
>
> - `HashMap<ResourceId, (Resource, Vec<ResourceId>)>`
> - `type R = RefCell<Resource>`, `Vec<Rc<R>>` and `Vec<(Weak<R>, Vec<Weak<R>>)>`

Ack these allow updates, so maybe not apples-to-apples.  Yet these are what someone naive/ignorant might land on - and it is where I was heading - until I saw you lib announced via "This week in Rust".

I suppose I was wondering if such alternatives are expected to be and order of magnitude slower, etc.

**Comment by mamcx** [comment]
> I suppose I was wondering if such alternatives are expected to be an order of magnitude slower, etc.

Because all the internal storage is on top of Vectors and the processing is lineal, it will be in theory the same as `Vec`. 

The alternatives you put are more or less Linked List or less performant versions of Arenas (so, it need to "jump around"). I don't have the exact numbers but you can read about how much improvement is going this way:

https://stackoverflow.com/questions/19039972/linked-list-vs-vector

**Comment by taqtiqa-mark** [comment]
:+1:
